torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \
  --vla_path "openvla/openvla-7b" \
  --data_root_dir "/home/ubuntu/curve/tensorflow_datasets" \
  --dataset_name "ck_counter_dataset" \
  --run_root_dir "/home/ubuntu/training" \
  --lora_rank 32 \
  --batch_size 8 \
  --grad_accumulation_steps 1 \
  --learning_rate 5e-4 \
  --image_aug True \
  --wandb_project openvla_oft \
  --wandb_entity rcdotson \
  --run_id_note ck_counter_joint
