torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \
  --vla_path "openvla/openvla-7b" \
  --data_root_dir "/home/aware/tensorflow_datasets" \
  --dataset_name "sim_countertop_activities_dataset" \
  --run_root_dir "/home/aware/training" \
  --adapter_tmp_dir "/home/aware/training_tmp" \
  --lora_rank 32 \
  --batch_size 2 \
  --grad_accumulation_steps 4 \
  --learning_rate 5e-4 \
  --image_aug True \
  --wandb_project openvla_lora \
  --wandb_entity rcdotson \
  --save_steps 5000 \
  --run_id_note joint
